### ISSUE TITLE
MiNA plugin not working: ImportError: compiled unit contains version 37 code (38 required)

### ISSUE THREAD

**Issue by maiich-MF** [StuartLab/MiNA#21]
Hi! 
I have an issue with Mina plugin. I get the error that was reported before, but none of the answers help me. I have tried updating Fiji, uninstalling it, removing the plugins, but nothing helps. 
Any idea? It used to work on my laptop and work computer, but now i can't run it on any computer at work. 
![fiji](https://user-images.githubusercontent.com/71819058/94125154-4b2b6880-fe56-11ea-961b-e9e2c2d6948b.jpg)

**Comment by imagejan** [comment]
The same issue has been reported [on the image.sc forum](https://forum.image.sc/t/mina-mitochondrial-network-analysis-error-plugins/42831?u=imagejan).

**Comment by RodoVJ** [comment]
Thanks @imagejan. @maiich-MF , as Alex.h pointed out in the forum, a new version of MiNA is available. Try installing MiNA 3.0.0 by following the installation instructions of the README. If you get the same error after this it may be because you’re still running the same old version since they have the same name and are both located under StuartLab. If this is the case, delete the StuartLab folder inside Plugins or change the name of StuartLab/MiNA_scripts/MiNA_Analyze_Morphology.py (which is the old version) to something else so you can differentiate between the two. Check the closed issues, someone else had the same problem.

All the best,
Rodrigo

**Comment by maiich-MF** [comment]
Thank you @RodoVJ. This did solve the problem, but now I get the new error. I followed the instructions in README by letter, but now this shows up. Didn't find this error in closed issues.

![Brez naslova](https://user-images.githubusercontent.com/71819058/94142405-846fd280-fe6e-11ea-846b-4670da5a19cb.jpg)

**Comment by RodoVJ** [comment]
@maiich-MF  can you tell me what operating system you are using, the version of ImageJ (If you go to Help>Update ImageJ... it will tell you the current version) and the version of FIJI? Also, when does this error occur? Are you able to see the main interface of MiNA or are you not able to see it at all?

**Comment by maiich-MF** [comment]
@RodoVJ I'm using Win10, ImageJ version is v1.53e, I reinstalled FIJI today (from https://fiji.sc/). The main interface of MiNA opens normally, I can change the parameters, but when I try to process the cell (imported via BioFormats - .czi picture format) this error occures after a few seconds.

**Comment by RodoVJ** [comment]
@maiich-MF based on this [forum post](https://forum.image.sc/t/after-fiji-update-scripts-dont-work-right/31090/15), it seems that this problem might arise if you have full-width characters (such as Chinese or Japanese) in a path that ImageJ might be using to run Jython scripts. Would you happen to have any of these types of characters in a path where you have FIJI installed?

**Comment by maiich-MF** [comment]
@RodoVJ I tried moving the FIJI app map directly on desktop, and now it works. Thank you for all your help! You saved my life! :)

**Comment by RodoVJ** [comment]
No worries @maiich-MF , I’m glad it worked!
