### ISSUE TITLE
unable to execute plugin after downloading git zip file into fiji.app file

### ISSUE THREAD

**Issue by klai001** [StuartLab/MiNA#30]
Hi all
previously i already had MiNA plugin running on my fiji;
however i wanted to update the latest verison of the plugin and 
i followed the installation steps of the plugin according to this repo

however;
when i run MiNA
i get this output on command log

 File "Plugins/StuartLab/MiNA_Scripts/MiNA_Analyze_Morphology.py", line 20, in <module>
ImportError: compiled unit contains version 37 code (38 required): C:\Users\k\Downloads\fiji-win64\Fiji.app\jars\Lib\eztables\__init__$py.class

may i know how do i resolve this?

**Comment by RodoVJ** [comment]
Hi,
it may be because you’re still running the same old version since they have the same name and are both located under StuartLab. If this is the case, delete the StuartLab folder inside Plugins or change the name of StuartLab/MiNA_scripts/MiNA_Analyze_Morphology.py (which is the old version) to something else so you can differentiate between the two.

**Comment by klai001** [comment]
Hi
I did what you recommended but i got the same error;
additionally; 
I deleted my entire ij file and reinstalled everything again and the same error persists;
please advise;
thanks

**Comment by klai001** [comment]
got it working after deleting the second time and reinstalling 3.0
